# Generated by Django 3.2 on 2021-07-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_alter_mycustomuser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycustomuser',
            options={'permissions': [('confirmed_user', 'can visit the website')]},
        ),
    ]
