# Generated by Django 3.2 on 2021-07-19 23:52

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customuser', '0003_alter_mycustomuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGroups',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='mycustomuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already in use, please log in or reset your password.'}, max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
