# Generated by Django 3.2 on 2021-10-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customuser', '0005_mycustomuser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='customuser', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='MyGroups',
        ),
    ]
