# Generated by Django 3.2 on 2021-07-22 22:57

from django.db import migrations, models
import galleries.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidimage',
            name='img',
            field=models.ImageField(blank=True, upload_to=galleries.models.KidImage.upload_kid_image),
        ),
    ]
