# Generated by Django 3.2 on 2021-07-23 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_alter_kidimage_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kidimage',
            old_name='img',
            new_name='image',
        ),
    ]
