# Generated by Django 3.2 on 2021-07-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_rename_img_kidimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidimage',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kidimages', to='galleries.imagegallery'),
        ),
    ]
