# Generated by Django 3.2 on 2021-08-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_alter_kidimage_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kidimage',
            old_name='image',
            new_name='thekidimage',
        ),
        migrations.AddField(
            model_name='kidimage',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='thumbs'),
        ),
    ]
