# Generated by Django 3.2 on 2021-10-05 10:03

from django.db import migrations, models
import galleries.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_auto_20210828_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidimage',
            name='thekidimage',
            field=models.ImageField(blank=True, unique=True, upload_to=galleries.models.KidImage.upload_kid_image),
        ),
    ]
