# Generated by Django 3.2 on 2021-10-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('slug', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=64)),
                ('ingredients', models.TextField()),
                ('method', models.TextField()),
                ('slug', models.CharField(default='', max_length=64)),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeplanner.cookbook')),
            ],
        ),
    ]
