# Generated by Django 3.2 on 2021-10-22 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=64)),
                ('pen_pic', models.ImageField(blank=True, upload_to='author_pics')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=64)),
                ('cover', models.ImageField(blank=True, upload_to='covers')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('author', models.ManyToManyField(blank=True, related_name='authors_book', to='therecipes.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=64)),
                ('ingredient_qty', models.IntegerField()),
                ('ingredient_unit', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=64)),
                ('ingredients', models.TextField()),
                ('method', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ManyToManyField(blank=True, to='therecipes.Category')),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therecipes.cookbook')),
            ],
        ),
    ]
